apache:
    build: apache
    container_name: apache
    ports :
        - "80:80"
    volumes:
        - ./apache/www:/var/www/html/
    links:
        - mysql
phpmyadmin:
    image: corbinu/docker-phpmyadmin
    container_name: phpmyadmin
    ports :
        - "8080:80"
    environment:
        - MYSQL_USERNAME=root
        - MYSQL_PASSWORD=toor
    links:
        - mysql:mysql
mysql:
    image: mysql:5.5
    container_name: mysql
    ports:
        - "3306:3306"
    volumes:
        - ./mysql/conf.d:/etc/mysql/conf.d/
        - ./mysql/db:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=toor
        - MYSQL_USER=simpleuser
        - MYSQL_PASSWORD=simpleuser
